echo "Scenario 1: Happy flow - country first language second - http://localhost:8080/register?country=CA&language=fr&p1=v1&p2=v2"
curl "http://localhost:8080/register?country=CA&language=fr&p1=v1&p2=v2"
echo "Scenario 2: Happy flow - language first country second - http://localhost:8080/register?language=fr&country=CA&p1=v1&p2=v2"
curl "http://localhost:8080/register?language=fr&country=CA&p1=v1&p2=v2"
echo "Scenario 3: no country, no language - http://localhost:8080/register?p1=v1&p2=v2"
curl "http://localhost:8080/register?p1=v1&p2=v2"
echo "Scenario 4: no params - requires a "?" at the end to work - http://localhost:8080/register"
curl "http://localhost:8080/register?"
echo "scenario 6 - only language and other params - http://localhost:8080/register?language=fr&p1=v1&p2=v2"
curl "http://localhost:8080/register?language=fr&p1=v1&p2=v2"
echo "scenario 7 - only country and other params - http://localhost:8080/register?country=CA&p1=v1&p2=v2"
curl "http://localhost:8080/register?country=CA&p1=v1&p2=v2"
echo "scenario 8 - only country + language - http://localhost:8080/register?country=CA&language=fr"
curl "http://localhost:8080/register?country=CA&language=fr"
echo "scenario 9 - only language + country - http://localhost:8080/register?language=fr&country=CA"
curl "http://localhost:8080/register?language=fr&country=CA"
echo "scenario 10 - mixed parameters - language first country later - http://localhost:8080/register?language=fr&country=CA&p1=v1&p2=v2"
curl "http://localhost:8080/register?p1=v1&language=fr&country=CA&p2=v2"
echo  "scenario 11 - mixed parameters - country first language later - http://localhost:8080/register?p1=v1&country=CA&language=fr&p2=v2"
curl "http://localhost:8080/register?p1=v1&country=CA&language=fr&p2=v2"
echo "scenario 12 - mixed parameters - country first language later - http://localhost:8080/register?p1=v1&country=CA&p3=p3&language=fr&p2=v2"
curl "http://localhost:8080/register?p1=v1&country=CA&p3=p3&language=fr&p2=v2"
echo "scenario 12 - mixed parameters - country first language later - http://localhost:8080/register?p1=v1&country=CA&p3=p3&language=fr&p2=v2"
curl "http://localhost:8080/register?p1=v1&country=CA&p3=p3&language=fr&p2=v2"

# Path: applications/kokcon-apache/rewrite_test.sh